import Head from 'next/head';
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Provider } from 'react-redux';
import store, { persistor } from 'store/store';
import { PersistGate } from 'redux-persist/integration/react';
import RouteGuard from 'Navigation/RouteGuard';

config.autoAddCss = false;

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Second Hand</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Provider store={store}>
        <PersistGate persistor={persistor}>
          <RouteGuard>
            <Component {...pageProps} />
          </RouteGuard>
        </PersistGate>
      </Provider>
    </>
  );
}

export default MyApp;
